[project]
name = "sottovoce"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "RealtimeSTT>=0.3.104",
    "python-dotenv>=1.1.1",
]

[dependency-groups]
dev = [
    "coveralls>=4.0.1",
    "ruff>=0.12.10",
]
